name: Build and push Docker image to Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: blog-server
  CONTAINER_NAME: blog-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.IMAGE_NAME}}:latest

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.IMAGE_NAME}}:latest
            sudo docker stop ${{env.CONTAINER_NAME}} || true
            sudo docker rm ${{env.CONTAINER_NAME}} || true
            sudo docker run -e MONGO_URI="${{ secrets.MONGO_URI }}" -d -p 4000:4000 -p 4040:4040 --name ${{env.CONTAINER_NAME}} ${{ secrets.DOCKER_HUB_USERNAME }}/${{env.IMAGE_NAME}}:latest
