name: Build and push Docker image to Docker Hub

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: blog-server
  CONTAINER_NAME: blog-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest

      - name: SSH deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          # port: ${{ secrets.SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            docker run -e MONGO_URI=${{ secrets.MONGO_URI }} -d -p 3000:3000 4040:4040 --name ${} $CONTAINER_NAME ${{ secrets.DOCKER_HUB_USERNAME }}/$IMAGE_NAME:latest
